import type { AllergenIconCollection, AllergenIconManifestEntry } from '../../types'

export const erudusCollection = {
  "id": "erudus",
  "label": "Erudus",
  "description": "Erudus allergen and dietary SVG icons.",
  "license": "MIT",
  "sourceUrl": "https://github.com/Erudus/erudus-icons",
  "iconCount": 59,
  "importPath": "@kaspernowak/allergen-icons/collections/erudus"
} as const satisfies AllergenIconCollection

export const erudusIcons = [
  {
    "name": "celery",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CeleryIcon",
    "title": "Celery",
    "fileName": "celery.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CeleryIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/celery.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "cereal",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CerealIcon",
    "title": "Cereal",
    "fileName": "cereal.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CerealIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/cereal.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-celery",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleCeleryIcon",
    "title": "Circle Celery",
    "fileName": "circle-celery.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleCeleryIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-celery.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-cereal",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleCerealIcon",
    "title": "Circle Cereal",
    "fileName": "circle-cereal.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleCerealIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-cereal.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-crustaceans",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleCrustaceansIcon",
    "title": "Circle Crustaceans",
    "fileName": "circle-crustaceans.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleCrustaceansIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-crustaceans.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-eggs",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleEggsIcon",
    "title": "Circle Eggs",
    "fileName": "circle-eggs.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleEggsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-eggs.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-fish",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFishIcon",
    "title": "Circle Fish",
    "fileName": "circle-fish.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFishIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-fish.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-barley",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromBarleyIcon",
    "title": "Circle Free From Barley",
    "fileName": "circle-free-from-barley.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromBarleyIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-barley.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-celery",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromCeleryIcon",
    "title": "Circle Free From Celery",
    "fileName": "circle-free-from-celery.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromCeleryIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-celery.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-crustacea",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromCrustaceaIcon",
    "title": "Circle Free From Crustacea",
    "fileName": "circle-free-from-crustacea.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromCrustaceaIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-crustacea.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-eggs",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromEggsIcon",
    "title": "Circle Free From Eggs",
    "fileName": "circle-free-from-eggs.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromEggsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-eggs.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-fish",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromFishIcon",
    "title": "Circle Free From Fish",
    "fileName": "circle-free-from-fish.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromFishIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-fish.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-gluten",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromGlutenIcon",
    "title": "Circle Free From Gluten",
    "fileName": "circle-free-from-gluten.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromGlutenIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-gluten.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-lactose",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromLactoseIcon",
    "title": "Circle Free From Lactose",
    "fileName": "circle-free-from-lactose.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromLactoseIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-lactose.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-lupin",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromLupinIcon",
    "title": "Circle Free From Lupin",
    "fileName": "circle-free-from-lupin.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromLupinIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-lupin.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-milk",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromMilkIcon",
    "title": "Circle Free From Milk",
    "fileName": "circle-free-from-milk.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromMilkIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-milk.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-molluscs",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromMolluscsIcon",
    "title": "Circle Free From Molluscs",
    "fileName": "circle-free-from-molluscs.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromMolluscsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-molluscs.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-mustard",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromMustardIcon",
    "title": "Circle Free From Mustard",
    "fileName": "circle-free-from-mustard.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromMustardIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-mustard.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-nuts",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromNutsIcon",
    "title": "Circle Free From Nuts",
    "fileName": "circle-free-from-nuts.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromNutsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-nuts.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-oats",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromOatsIcon",
    "title": "Circle Free From Oats",
    "fileName": "circle-free-from-oats.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromOatsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-oats.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-peanuts",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromPeanutsIcon",
    "title": "Circle Free From Peanuts",
    "fileName": "circle-free-from-peanuts.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromPeanutsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-peanuts.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-rye",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromRyeIcon",
    "title": "Circle Free From Rye",
    "fileName": "circle-free-from-rye.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromRyeIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-rye.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-sesame",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromSesameIcon",
    "title": "Circle Free From Sesame",
    "fileName": "circle-free-from-sesame.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromSesameIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-sesame.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-soya",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromSoyaIcon",
    "title": "Circle Free From Soya",
    "fileName": "circle-free-from-soya.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromSoyaIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-soya.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-sulphur-dioxide",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromSulphurDioxideIcon",
    "title": "Circle Free From Sulphur Dioxide",
    "fileName": "circle-free-from-sulphur-dioxide.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromSulphurDioxideIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-sulphur-dioxide.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-free-from-wheat",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleFreeFromWheatIcon",
    "title": "Circle Free From Wheat",
    "fileName": "circle-free-from-wheat.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleFreeFromWheatIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-free-from-wheat.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-gluten",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleGlutenIcon",
    "title": "Circle Gluten",
    "fileName": "circle-gluten.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleGlutenIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-gluten.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-halal",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleHalalIcon",
    "title": "Circle Halal",
    "fileName": "circle-halal.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleHalalIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-halal.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-kosher",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleKosherIcon",
    "title": "Circle Kosher",
    "fileName": "circle-kosher.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleKosherIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-kosher.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-lupin",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleLupinIcon",
    "title": "Circle Lupin",
    "fileName": "circle-lupin.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleLupinIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-lupin.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-milk",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleMilkIcon",
    "title": "Circle Milk",
    "fileName": "circle-milk.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleMilkIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-milk.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-molluscs",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleMolluscsIcon",
    "title": "Circle Molluscs",
    "fileName": "circle-molluscs.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleMolluscsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-molluscs.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-mustard",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleMustardIcon",
    "title": "Circle Mustard",
    "fileName": "circle-mustard.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleMustardIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-mustard.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-nuts",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleNutsIcon",
    "title": "Circle Nuts",
    "fileName": "circle-nuts.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleNutsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-nuts.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-peanuts",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CirclePeanutsIcon",
    "title": "Circle Peanuts",
    "fileName": "circle-peanuts.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CirclePeanutsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-peanuts.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-sesame",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleSesameIcon",
    "title": "Circle Sesame",
    "fileName": "circle-sesame.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleSesameIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-sesame.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-so2",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleSo2Icon",
    "title": "Circle SO2",
    "fileName": "circle-so2.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleSo2Icon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-so2.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-soya",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleSoyaIcon",
    "title": "Circle Soya",
    "fileName": "circle-soya.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleSoyaIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-soya.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-vegan",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleVeganIcon",
    "title": "Circle Vegan",
    "fileName": "circle-vegan.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleVeganIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-vegan.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-vegetarian",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleVegetarianIcon",
    "title": "Circle Vegetarian",
    "fileName": "circle-vegetarian.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleVegetarianIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-vegetarian.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "circle-very-low-gluten",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CircleVeryLowGlutenIcon",
    "title": "Circle Very Low Gluten",
    "fileName": "circle-very-low-gluten.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CircleVeryLowGlutenIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/circle-very-low-gluten.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "coeliac",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CoeliacIcon",
    "title": "Coeliac",
    "fileName": "coeliac.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CoeliacIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/coeliac.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "crustaceans",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "CrustaceansIcon",
    "title": "Crustaceans",
    "fileName": "crustaceans.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/CrustaceansIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/crustaceans.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "eggs",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "EggsIcon",
    "title": "Eggs",
    "fileName": "eggs.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/EggsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/eggs.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "fish",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "FishIcon",
    "title": "Fish",
    "fileName": "fish.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/FishIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/fish.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "gluten",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "GlutenIcon",
    "title": "Gluten",
    "fileName": "gluten.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/GlutenIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/gluten.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "halal",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "HalalIcon",
    "title": "Halal",
    "fileName": "halal.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/HalalIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/halal.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "kosher",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "KosherIcon",
    "title": "Kosher",
    "fileName": "kosher.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/KosherIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/kosher.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "lupin",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "LupinIcon",
    "title": "Lupin",
    "fileName": "lupin.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/LupinIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/lupin.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "milk",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "MilkIcon",
    "title": "Milk",
    "fileName": "milk.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/MilkIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/milk.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "molluscs",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "MolluscsIcon",
    "title": "Molluscs",
    "fileName": "molluscs.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/MolluscsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/molluscs.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "mustard",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "MustardIcon",
    "title": "Mustard",
    "fileName": "mustard.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/MustardIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/mustard.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "nuts",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "NutsIcon",
    "title": "Nuts",
    "fileName": "nuts.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/NutsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/nuts.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "peanuts",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "PeanutsIcon",
    "title": "Peanuts",
    "fileName": "peanuts.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/PeanutsIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/peanuts.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "sesame",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "SesameIcon",
    "title": "Sesame",
    "fileName": "sesame.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/SesameIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/sesame.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "so2",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "So2Icon",
    "title": "SO2",
    "fileName": "so2.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/So2Icon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/so2.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "soya",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "SoyaIcon",
    "title": "Soya",
    "fileName": "soya.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/SoyaIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/soya.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "vegan",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "VeganIcon",
    "title": "Vegan",
    "fileName": "vegan.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/VeganIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/vegan.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  },
  {
    "name": "vegetarian",
    "collectionId": "erudus",
    "collectionLabel": "Erudus",
    "componentName": "VegetarianIcon",
    "title": "Vegetarian",
    "fileName": "vegetarian.svg",
    "importPath": "@kaspernowak/allergen-icons/icons/erudus/VegetarianIcon",
    "svgPath": "@kaspernowak/allergen-icons/svg/erudus/vegetarian.svg",
    "viewBox": "0 0 64 64",
    "defaultPrimaryColor": "#000000",
    "defaultSecondaryColor": "#000000"
  }
] as const satisfies readonly AllergenIconManifestEntry[]
