export type * from './types'
export { createAllergenIcon } from './createAllergenIcon'
export { default as CeleryIcon } from './icons/CeleryIcon'
export { default as CrustaceanIcon } from './icons/CrustaceanIcon'
export { default as EggIcon } from './icons/EggIcon'
export { default as FishIcon } from './icons/FishIcon'
export { default as GlutenIcon } from './icons/GlutenIcon'
export { default as LupinIcon } from './icons/LupinIcon'
export { default as MilkIcon } from './icons/MilkIcon'
export { default as MolluscIcon } from './icons/MolluscIcon'
export { default as MustardIcon } from './icons/MustardIcon'
export { default as NutsIcon } from './icons/NutsIcon'
export { default as PeanutIcon } from './icons/PeanutIcon'
export { default as SesameIcon } from './icons/SesameIcon'
export { default as SoyaIcon } from './icons/SoyaIcon'
export { default as SulphiteIcon } from './icons/SulphiteIcon'
